version: '3'
services:
    db:
        image: mysql:5.7
        ports:
            - "33061:3306"
        volumes:
            - ./backend/scripts/development/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: dev_mc_task
            MYSQL_ROOT_PASSWORD: dev_mc_task
            MYSQL_DATABASE: dev_task_list
        command: 
            --init-file /data/application/init.sql
            --skip-name-resolve
    backend:
        image: node:10.20.1
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
        volumes:
            - ./backend:/backend
        ports: 
            - 3000:3000
        working_dir: /backend
        command: bash -c "./start.sh && npm start"
    frontend:
        image: node:10.20.1
        depends_on: 
            - backend
        volumes: 
            - ./frontend:/frontend
        ports: 
            - 8080:8080
        working_dir: /frontend
        command: bash -c "./start.sh && npm run serve"